version: "3.5"
services:
  goerli-geth.dnp.dappnode.eth:
    image: "goerli-geth.dnp.dappnode.eth:0.4.12"
    build:
      context: .
      args:
        UPSTREAM_VERSION: v1.10.25
    volumes:
      - "goerli:/goerli"
    ports:
      - "30803:30803/tcp"
      - "30803:30803/udp"
      - "8535:8545"
      - "8536:8546"
    restart: unless-stopped
    environment:
      - "EXTRA_OPTION=--goerli --http --http.corsdomain '*' --http.addr 0.0.0.0 --http.api admin,eth,debug,net,txpool,personal,web3 --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.origins * --ws.api admin,eth,debug,net,txpool,personal,web3 --syncmode 'snap' --metrics"
      - P2P_PORT=30803
      - SYNCMODE
volumes:
  goerli: {}
