version: "3.5"
services:
  goerli-geth.dnp.dappnode.eth:
    image: "goerli-geth.dnp.dappnode.eth:0.4.12"
    build:
      context: .
      args:
        UPSTREAM_VERSION: v1.10.19
    volumes:
      - "goerli:/goerli"
    ports:
      - "30303"
      - 30303/udp
      - 30304/udp
    restart: always
    environment:
      - "EXTRA_OPTIONS=--http.api eth,net,web3,txpool"
      - SYNCMODE
volumes:
  goerli: {}
