version: "3.5"
services:
  goerli-geth.dnp.dappnode.eth:
    image: "goerli-geth.dnp.dappnode.eth:0.4.12"
    build:
      context: .
      args:
        UPSTREAM_VERSION: v1.10.20
    volumes:
      - "goerli:/goerli"
    ports:
      - "30308:30308/tcp"
      - "30308:30308/udp"
    restart: always
    environment:
      - "EXTRA_OPTIONS=--http.api eth,net,web3,txpool"
      - P2P_PORT=30308
      - SYNCMODE
volumes:
  goerli: {}
